[doc]rfct] example usage of list jobs
funkyfuture/deck-chores pull request #121
Opened 2023-06-21 14:10 UTC by M3ssman

Concerning issue #120

2024-10-13 15:43 UTC, funkyfuture requested changes
thank you Uwe, i was quiet struggling with the verbosity of yor extension. do you think my proposals of change would still be helpful?

the docs aren't supposed to inform about processes, signals, containers, logs and so on; it assumes users are oriented i these regards and rather consult the resources that deal with the used technologies.

2024-10-13 15:43 UTC, funkyfuture commented on docs/usage.rst
> +with a running *deck-chores* container named ``deck-chores_officer_1``, one needs to call::
```suggestion
with a running *deck-chores* from a ``docker compose`` project, one needs to call::
```

2024-10-13 15:43 UTC, funkyfuture commented on docs/usage.rst
> +active job.
```suggestion
The output appears in ``deck-chores``' log target, that are the container's logs when it runs within
one.
```

here it gets just too verbose for my taste and the consistency of the deliberately compact docs.

2024-10-13 18:15 UTC, M3ssman commented
Yes of course I appreciate the feedback. 
For an experienced user it was way too verbose, but blame it on my educational point-of-view :slightly_smiling_face:

2024-10-16 09:30 UTC, funkyfuture commented
a'ight, i'm bad at usign web based interfaces, hence i reworked the changes locally and merged all w/ 85a1da6ff7085ebbfc4108ed92bc9af879a8541b.

> but blame it on my educational point-of-view 🙂

i think it makes sense to have various types of user-facing documentation. as maintainer i only want to focus on the reference. i wouldn't say no to amend user stories / scenarios documentation chapters that take a narrative  approach.

2024-10-16 09:30 UTC, closed without merging