Reverting to 3.12 until RTD supports 3.13
funkyfuture/deck-chores pull request #152
Opened 2024-10-16 13:56 UTC by tabedzki

2024-10-16 17:19 UTC, funkyfuture requested changes
please don't change builds (Dockerfiles' base images) and the workflow. they have no impact on the RTD build.

2024-10-16 17:19 UTC, funkyfuture commented on .readthedocs.yml
amending a list item `furo` to `python.install` should solve the build failure.

2024-10-16 17:37 UTC, tabedzki commented
If the pyproject.toml and the poetry.lock are set for Python 3.13, would the build for RTD fail due to being 3.12?

2024-10-17 14:56 UTC, funkyfuture commented
> If the pyproject.toml and the poetry.lock are set for Python 3.13, would the build for RTD fail due to being 3.12?

yes, because Python package installers would deny an installation of the project itself.

i'm closing this pr in favor of #154.

2024-10-17 14:56 UTC, closed without merging